services:
  category_prediction:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    volumes:
      - .:/app
    restart: unless-stopped